### ISSUE TITLE
Clash with Compose Multiplatform 1.6.0-beta01

### ISSUE THREAD

**Issue by chrisbanes** [gmazzo/gradle-buildconfig-plugin#131]
It seems that the Compose Multiplatform plugin in 1.6.0-beta01 now uses KotlinPoet, which seems to clash with this plugin.

The issue is differing version, this plugin uses 1.16.0 (and new APIs), but CMP uses 1.14.2 ([see here](https://github.com/JetBrains/compose-multiplatform/blob/master/gradle-plugins/gradle/libs.versions.toml#L11)). Gradle seems to force KotlinPoet 1.14.2 on the classpath, which means that this plugin ends up crashing:

```
Caused by: java.lang.NoSuchMethodError: 'java.io.File com.squareup.kotlinpoet.FileSpec.writeTo(java.io.File)'
	at com.github.gmazzo.buildconfig.generators.BuildConfigKotlinGenerator.execute(BuildConfigKotlinGenerator.kt:60)
	at com.github.gmazzo.buildconfig.generators.BuildConfigKotlinGenerator.execute(BuildConfigKotlinGenerator.kt:45)
	at com.github.gmazzo.buildconfig.BuildConfigTask.generateBuildConfigFile(BuildConfigTask.kt:59)
```

## Workaround

There's probably a better way to achieve this via `dependencyResolution`, but for now I've forced the right version onto the classpath via the following in my root `build.gradle.kts`

``` kotlin
buildscript {
  dependencies {
    // Yuck. Need to force kotlinpoet:1.16.0 as that is what buildconfig uses.
    // CMP 1.6.0-x uses kotlinpoet:1.14.x. Gradle seems to force 1.14.x which then breaks
    // buildconfig.
    classpath("com.squareup:kotlinpoet:1.16.0")
  }
}
```

**Comment by chrisbanes** [comment]
Yep, sounds good. I mostly opened this as a FYI for others searching when they hit this.
