### ISSUE TITLE
Proguard issue when running release KMM

### ISSUE THREAD

**Issue by JacobCube** [gmazzo/gradle-buildconfig-plugin#177]
This is an error I get when running the composeApp:proguardReleaseJars script in KMM ` Warning: class [chatenrichment/composeapp/BuildConfig.class] unexpectedly contains class [Chatenrichment.composeApp.BuildConfig]`.
I'm using proguard 7.2.2 and I tried even adding `-keep class Chatenrichment.composeApp.BuildConfig { *; }` to proguardRules but no luck there.

Perhaps I'm doing something wrong and it has nothing to do with this library, but I'm unsure, as no other library-generated file causes this issue.

**Comment by JacobCube** [comment]
It seems to be working now, unsure of what caused it.

**Comment by JacobCube** [comment]
`Warning: there were 1 classes in incorrectly named files.
         You should make sure all file names correspond to their class names.
         The directory hierarchies must correspond to the package hierarchies.
         (https://www.guardsquare.com/proguard/manual/troubleshooting#unexpectedclass)
         If you don't mind the mentioned classes not being written out,
         you could try your luck using the '-ignorewarnings' option.
Unexpected error
java.io.IOException: Please correct the above warnings first.
	at proguard.InputReader.execute(InputReader.java:192) ~[proguard-base-7.4.0.jar:7.4.0]
	at proguard.pass.PassRunner.run(PassRunner.java:24) ~[proguard-base-7.4.0.jar:7.4.0]
	at proguard.ProGuard.readInput(ProGuard.java:333) ~[proguard-base-7.4.0.jar:7.4.0]
	at proguard.ProGuard.execute(ProGuard.java:124) ~[proguard-base-7.4.0.jar:7.4.0]
	at proguard.ProGuard.main(ProGuard.java:651) ~[proguard-base-7.4.0.jar:7.4.0]

> Task :composeApp:proguardReleaseJars FAILED`

How to reproduce: run gradle script packageReleaseDmg with Java 17 on a KMP project and Proguard set to 7.4.0 version.

**Comment by JacobCube** [comment]
Setting custom packageName and class name fixed the issue
